### ISSUE TITLE
Build (linking) error on macOS Ventura 13.5.2 Apple M2

### ISSUE THREAD

**Issue by Meowuu7** [LuisaGroup/LuisaCompute#106]
**Describe the bug**
Build (linking) error on macOS Ventura 13.5.2 Apple M2

**To Reproduce**

I run the following commands to build the repo
```bash
cmake -S . -B ./build -D CMAKE_BUILD_TYPE=Release 
cmake  --build  ./build
```
Everything was ok until the linking error I encountered when the building was almost done
![Screenshot 2023-12-03 at 18 46 10](https://github.com/LuisaGroup/LuisaCompute/assets/50799886/d7339cbc-9df5-4eef-857d-b99ff10957ff)

![Screenshot 2023-12-03 at 18 43 03](https://github.com/LuisaGroup/LuisaCompute/assets/50799886/5cc509df-4c53-4bf2-a2a5-d53045e17141)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5.2 Apple M2

**Additional context**
I tried to find solutions for such linking error but they couldn't work for me. 
For instance, related issues are raised in [https://github.com/microsoft/onnxruntime/issues/11545](https://github.com/microsoft/onnxruntime/issues/11545), [https://forum.qt.io/topic/140732/undefined-symbols-for-architecture-arm64](https://forum.qt.io/topic/140732/undefined-symbols-for-architecture-arm64), [https://forum.qt.io/topic/140732/undefined-symbols-for-architecture-arm64](https://forum.qt.io/topic/140732/undefined-symbols-for-architecture-arm64).

**Comment by Mike-Leo-Smith** [comment]
Hi @Meowuu7 

It looks like you have a `x86` version of `Qt` installed and `CMake` is finding this wrong one. Some solutions to consider:

- Disable the `Qt`-interop test by commenting out `src/tests/CMakeLists.txt` line 169-184, so the test will not be built and `Qt` will not be linked to. Or,
- Specify the correct installation path to `Qt` when you config CMake.

**Comment by Mike-Leo-Smith** [comment]
I would also add an option to manually disable the GUI tests that might depend on system libraries.

**Comment by Meowuu7** [comment]
Hi, thank you for your help. I've disabled `Qt` and have built the project successfully. 
But when I tried to run a test example under the `build/bin` folder, e.g. `./test_helloworld`, the program will be killed with `zsh killed ./test_helloworld`  output in the bash but without any further information w.r.t what happened.

**Comment by Meowuu7** [comment]
So I went back to rebuild the project using the `bootstrap.py` script:  
```bash
python bootstrap.py cmake -f metal -b
```
(`Qt` is still disabled)
However I run into a lot of errors respecting the architecture like:
![Screenshot 2023-12-03 at 20 22 51](https://github.com/LuisaGroup/LuisaCompute/assets/50799886/8632b817-a1a8-45e6-be98-5bdceeb2debf)

**Comment by Meowuu7** [comment]
When I tried to build it on a Ubuntu 20.04, I encountered with this problem
```bash
error: ‘construct_at’ is not a member of ‘std’
  104 |     return std::construct_at(allocate_with_allocator<T>(), std::forward<Args>(args)...);
 ```
 Is it related to cmake/g++/gcc version?
 I use `cmake 3.23.0`, `g++,gcc 9.4.0`.

**Comment by Meowuu7** [comment]
I've tried my best but cannot compile the project at all when including `tests` either on the Ubuntu platform or the macOS. 
Many undefined symbols problems come out:
![Screenshot 2023-12-03 at 22 43 18](https://github.com/LuisaGroup/LuisaCompute/assets/50799886/4085d5d0-f977-4634-9d5c-61293d3e3753)
![Screenshot 2023-12-03 at 22 43 05](https://github.com/LuisaGroup/LuisaCompute/assets/50799886/9780c737-ff3e-4bc0-83f1-f06d339aeab7)

**Comment by Mike-Leo-Smith** [comment]
> Hi, thank you for your help. I've disabled `Qt` and have built the project successfully. But when I tried to run a test example under the `build/bin` folder, e.g. `./test_helloworld`, the program will be killed with `zsh killed ./test_helloworld` output in the bash but without any further information w.r.t what happened.

Would you help make sure that you're not running under the Rosetta mode? You can use the following command to verify the arch:
```shell
uname -m
``` 

If the output is something like `x86_64` then that would be the problem.

**Comment by Mike-Leo-Smith** [comment]
> When I tried to build it on a Ubuntu 20.04, I encountered with this problem
> 
> ```shell
> error: ‘construct_at’ is not a member of ‘std’
>   104 |     return std::construct_at(allocate_with_allocator<T>(), std::forward<Args>(args)...);
> ```
> 
> Is it related to cmake/g++/gcc version? I use `cmake 3.23.0`, `g++,gcc 9.4.0`.

`gcc-9` is insufficient to support the C++20 spec used by LuisaCompute. Please consider install a newer version, by, e.g., enabling the Ubuntu test toolchains PPA to install `gcc-13`:
```shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get -y install gcc-13 g++-13
```
And verify the installation with `gcc-13 -v`.
 
Then, when configuring CMake, specify `-D CMAKE_C_COMPILER=gcc-13` and `-D CMAKE_CXX_COMPILER=g++-13` to use this new toolchain.

**Comment by Mike-Leo-Smith** [comment]
> I've tried my best but cannot compile the project at all when including `tests` either on the Ubuntu platform or the macOS. Many undefined symbols problems come out: ![Screenshot 2023-12-03 at 22 43 18](https://private-user-images.githubusercontent.com/50799886/287525761-4085d5d0-f977-4634-9d5c-61293d3e3753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NzMxNzUsIm5iZiI6MTcwMTY3Mjg3NSwicGF0aCI6Ii81MDc5OTg4Ni8yODc1MjU3NjEtNDA4NWQ1ZDAtZjk3Ny00NjM0LTlkNWMtNjEyOTNkM2UzNzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA2NTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzE1MmViYzIyYmQyNmRjOWFkNWIxZDQzZmE1ODQ4MTU3N2I0NzliODQyZTlmZTExMmI5YzA2MTdjZTgxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.enDfWrUdvyWJu5QrPAkpmPZgDe4ORKJh7ynvOwjUfoE) ![Screenshot 2023-12-03 at 22 43 05](https://private-user-images.githubusercontent.com/50799886/287525765-9780c737-ff3e-4bc0-83f1-f06d339aeab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NzMxNzYsIm5iZiI6MTcwMTY3Mjg3NiwicGF0aCI6Ii81MDc5OTg4Ni8yODc1MjU3NjUtOTc4MGM3MzctZmYzZS00YmMwLTgzZjEtZjA2ZDMzOWFlYWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA2NTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZmYxMWQwNmVlMWU4OWU0ZWEwYWY1MTUzMWUzZDIyNjNmMGZmZmRjOWRmMjkxYTliNWQwNzhiN2ZiYzFiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MfB7n4LuwdYO0pLjgdgXnnnxyiKGsyiSrnvQ72YL6Wo)

It seems that the `dsl` feature is not enable with the `bootstrap.py` script. Please specify `-f dsl`.

**Comment by Meowuu7** [comment]
The project can be successfully compiled by 

- upgrading `nvidia-smi` to `545`
- and using the latest commit.

Thank you for your help.
