### ISSUE TITLE
test_denoiser crash with DX backend

### ISSUE THREAD

**Issue by hammerLWA** [LuisaGroup/LuisaCompute#108]
**Describe the bug**
test_denoiser crash with DX backend crash with CUDA_ERROR_INVALID_CONTEXT when cuImportExternalMemory is called in cuda_interop, test_cuda_dx_interop crash the same way.

**Desktop (please complete the following information):**
 - OS: Windows 2010
 - GPU: RTX2060

**Comment by Mike-Leo-Smith** [comment]
The DX-CUDA interop has not been fully implemented. You may try `test_denoiser` with the `cuda` or `cpu` backends.

**Comment by Mike-Leo-Smith** [comment]
The denoiser extension is now expected to work with the DX backend with the fixed DX-CUDA interop. Feel free to reopen this issue if anything goes wrong on your side :-)
