### ISSUE TITLE
当采用cmake作为构建工具，且依赖的 “Windows 10 SDK” 为 “10.0.19041.0” 时，关于DirectML的部分会编译失败

### ISSUE THREAD

**Issue by ymei-hana** [LuisaGroup/LuisaCompute#145]
**Describe the bug**
当依赖为 “Windows 10 SDK (10.0.19041.0)” 时，由于`sdkddkver.h`里是`#define WDK_NTDDI_VERSION NTDDI_WIN10_VB`
此时`LuisaCompute\src\backends\dx\DXApi\DirectML.h`里生效的是`#define DML_TARGET_VERSION 0x2000`
那么一些诸如要求`#if DML_TARGET_VERSION >= 0x2100`的代码会被忽略，故而导致编译失败

需要将依赖更改为 “Windows 10 SDK (10.0.20348.0)” 后，此时`sdkddkver.h`里是`#define WDK_NTDDI_VERSION  NTDDI_WIN10_FE`
此时`LuisaCompute\src\backends\dx\DXApi\DirectML.h`里生效的是`#define DML_TARGET_VERSION 0x3000`
那么可以编译通过

**To Reproduce**
1. 使用 “Visual Studio” 安装 “使用c++的桌面开发” 工作负荷
2. 在 “安装详细信息” 里，只安装上 “Windows 10 SDK (10.0.19041.0)”
3. 在`options.cmake`中带有`option(LUISA_COMPUTE_ENABLE_DX "Enable DirectX backend" ON)`时构建并编译

**Expected behavior**
1. 如果这是非预期行为的话，那么应该能在依赖 “Windows 10 SDK (10.0.19041.0)” 时编译通过
2. 如果这是预期行为，即只打算支持 “Windows 10 SDK (10.0.20348.0)” 或更高版本的 “Windows SDK” 的话，那么希望能在编译时给出更有引导性的错误提示

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Comment by ymei-hana** [comment]
我在xmake里尝试过用 “clang-cl” 工具链来编译，是会有关于windows sdk版本要求的提示的
不过xmake里写死了要 “>= 22000”，我试了将其改成 “>= 20348”，是可以成功编译

**Comment by Mike-Leo-Smith** [comment]
感谢反馈，已在 fc07fd4 增加 SDK 版本检查
