### ISSUE TITLE
LLVM backend: linking errors

### ISSUE THREAD

**Issue by ib00** [LuisaGroup/LuisaCompute#62]
I am having problems with LLVM backend.

I am using LLVM 15.0.5 on Linux and I get the following runtime error:

Failed to load dynamic module '/tmp/LuisaCompute/build/bin/libluisa-compute-backend-llvm.so', reason: /tmp/LuisaCompute/build/bin/libluisa-compute-backend-llvm.so: undefined symbol: _ZN4absl12lts_2022062318container_internal11kEmptyGroupE. [/tmp/LuisaCompute/src/core/platform.cpp:165]

Any ideas where the missing abseil symbol went?

**Comment by Mike-Leo-Smith** [comment]
Hi, @ib00.

We are currently transiting from `abseil` to [`robin-map`](https://github.com/Tessil/robin-map). Would you please

**Comment by Mike-Leo-Smith** [comment]
Hi, @ib00.

I've got no idea about the error, but, anyway, we are currently transiting from abseil to [robin-map](https://github.com/Tessil/robin-map), and hopefully the problem should be gone with the header-only library.

Would you please try
```bash
git pull && git submodule update --recursive --init
```
and re-compile the project to see if the issue persists?

**Comment by ib00** [comment]
Yes, this fixed the problem. Thank you!

**Comment by Mike-Leo-Smith** [comment]
Yeah!
