### ISSUE TITLE
Structured kernel parameter (with array) gets wrong result with dx backend

### ISSUE THREAD

**Issue by swfly** [LuisaGroup/LuisaCompute#65]
**Describe the bug**
Hello, as the title indicates, seems like dx backend cannot get correct data from a structured parameter for kernels.

**To Reproduce**
Run the following simple test:

```
#include <luisa-compute.h>
#include <dsl/sugar.h>

using namespace luisa;
using namespace luisa::compute;

struct foo
{
    luisa::float3 test1[2] = { { 0,0,0 },{ 0,0,0 } };
    luisa::float3 test2[2] = { { 0,0,0 } ,{ 0,0,0 } };
};
LUISA_STRUCT(foo, test1, test2) {};

int main(int args, char* argv[])
{
    std::vector<std::array<uint8_t, 4u>> download_image(1280 * 720);
    {
        Context context{ argv[0] };
        auto device = context.create_device("dx");
        auto stream = device.create_stream();
        auto device_image = device.create_image<float>(PixelStorage::BYTE4, 1280, 720, 0u);

        Kernel2D fill_image_kernel = [&](Var<foo> bar) noexcept
        {
            Var coord = dispatch_id().xy();
            device_image.write(coord, make_float4(bar.test2[1], 1.f));
        };
        auto fill_image = device.compile(fill_image_kernel);

        foo b;
        b.test2[1] = { 0,1,0 };

        stream
            << fill_image(b).dispatch(1280, 720)
            << device_image.copy_to(download_image.data())
            << synchronize();// Step 5: Synchronize the stream
    }

    Window window{ "Display", uint2{ 1280,720 } };
    window.set_key_callback([&](int key, int action) noexcept
    {
        if (action == GLFW_PRESS && key == GLFW_KEY_ESCAPE)
        {
            window.set_should_close();
        }
    });
    auto frame_count = 0u;
    window.run([&]
    {
        window.set_background(download_image.data(), uint2{ 1280,720 });
    });
}
```
**Expected behavior**
The popup window should show green pixels however now only black.

I am building on windows with vs 2019. The cuda backend works as expected. 
Actually I think it's not only a problem of using array in this structure. In my actual code I have a camera struct to pass to kernels and it apparently has alignment problem even without arrays.

**Comment by Mike-Leo-Smith** [comment]
Hi, @swfly 

Thanks for reporting this. I tried to fix the alignment issue with vector3 arrays in the DX backend in 38abe63, which should now pass the test code you provided.

For other alignment issues with structures,
> Actually I think it's not only a problem of using array in this structure. In my actual code I have a camera struct to pass to kernels and it apparently has alignment problem even without arrays.

Would you please provide the struct that causes the problem? Thanks!

**Comment by swfly** [comment]
Hi @Mike-Leo-Smith, great work yes it solves the problem!
For another case I just tested and still buggy... In the following code I just use the a similar struct with an extra bool variable instead, and it breaks the alignment immediately. When I saw the generated hlsl with ":8" I can feel the risk there (maybe I was wrong tho)!
```
#include <luisa-compute.h>
#include <dsl/sugar.h>

using namespace luisa;
using namespace luisa::compute;

struct foo
{
    bool bar = false;
    luisa::float3 test1 = { 0,0,0 };
};
LUISA_STRUCT(foo, bar, test1) {};

int main(int args, char* argv[])
{
    std::vector<std::array<uint8_t, 4u>> download_image(1280 * 720);
    {
        Context context{ argv[0] };
        auto device = context.create_device("dx");
        auto stream = device.create_stream();
        auto device_image = device.create_image<float>(PixelStorage::BYTE4, 1280, 720, 0u);

        Kernel2D fill_image_kernel = [&](Var<foo> bar) noexcept
        {
            Var coord = dispatch_id().xy();
            device_image.write(coord, make_float4(bar.test1, 1.f));
        };
        auto fill_image = device.compile(fill_image_kernel);

        foo b;
        b.test1 = { 0,1,0 };

        stream
            << fill_image(b).dispatch(1280, 720)
            << device_image.copy_to(download_image.data())
            << synchronize();// Step 5: Synchronize the stream
    }

    Window window{ "Display", uint2{ 1280,720 } };
    window.set_key_callback([&](int key, int action) noexcept
    {
        if (action == GLFW_PRESS && key == GLFW_KEY_ESCAPE)
        {
            window.set_should_close();
        }
    });
    auto frame_count = 0u;
    window.run([&]
    {
        window.set_background(download_image.data(), uint2{ 1280,720 });
    });
}
```

I think by looking at your mentioned commit I should be able to fix this myself since the problems look similar. But you are a lot more familiar with luisa, so if you happen to have time to fix, it'll be the best.

**Comment by Mike-Leo-Smith** [comment]
> so if you happen to have time to fix, it'll be the best.

OK! I'll look into this.

**Comment by Mike-Leo-Smith** [comment]
Hi, @swfly 

I think I've fixed the struct padding bug with `bool` members in 35b8ef6. Would you please verify if it now works with your structures?

**Comment by swfly** [comment]
Thanks @Mike-Leo-Smith 
Now my camera struct finally works and I don't need to use any workaround anymore. Let's close this issue.

**Comment by Mike-Leo-Smith** [comment]
Great!
