### ISSUE TITLE
Binary expression generates "--" and causes compiling error in dx

### ISSUE THREAD

**Issue by swfly** [LuisaGroup/LuisaCompute#66]
Hello during one of our test scenes the dx backend fails to compile due to a code line like 
```l670=(l665--4.371139e-08f);```
Seems dx compiler recognizes this line as "l665--" because it reports as "expected ) after --".
I propose to modify 67line of DxCodegen.cpp from```str << '-';``` to ```str << " - ";```, but not sure if this is a good idea.

**Comment by Mike-Leo-Smith** [comment]
Thanks for reporting this.

> I propose to modify 67line of DxCodegen.cpp from`str << '-';` to `str << " - ";`, but not sure if this is a good idea.

Yes, I think it’s a good idea!

**Comment by Mike-Leo-Smith** [comment]
Or may we could as well add parentheses around the operands to make it more robust…

**Comment by swfly** [comment]
> 

Yeah I think it's better to use the () approach.

**Comment by Mike-Leo-Smith** [comment]
OK, fixed in 4dc13c4.
