### ISSUE TITLE
BindlessArray fails to load correct values in DX with AMD GPUs

### ISSUE THREAD

**Issue by swfly** [LuisaGroup/LuisaCompute#67]
Hi, the following test code gives wrong result in AMD GPUs but works normally with Nvidia ones.

```
#include <luisa-compute.h>
#include <dsl/sugar.h>
#include <gui/window.h>


using namespace luisa;
using namespace luisa::compute;


int main(int argc, char* argv[])
{
	Context context{ argv[0] };
	auto device = context.create_device("dx");
	auto stream = device.create_stream();
	auto device_image1 = device.create_image<float>(PixelStorage::BYTE4, 1280, 720, 0u);
	auto bdls = device.create_bindless_array();
	auto buffer = device.create_buffer<float4>(4);
	std::vector<std::array<uint8_t, 4u>> d{ 1280 * 720 };
	std::vector<float4> a{ 4 };
	a[0] = { 1, 0, 0,1 };
	a[1] = { 0, 1, 0,1 };
	a[2] = { 0, 0, 1,1 };
	a[3] = { 1, 1, 1,1 };
	stream << buffer.copy_from(a.data())<<synchronize();
	bdls.emplace(0, buffer);
	stream << bdls.update() << synchronize();

	Kernel2D kernel = [&]()
	{
		Var coord = dispatch_id().xy();

		UInt i2 = ((coord.x / 15) % 4);
		auto vertexArray = bdls.buffer<float4>(0);
		Float4 p = vertexArray.read(i2);
		device_image1.write(coord, make_float4(p));
	};
	auto s = device.compile(kernel);
	stream
		<< s().dispatch(1280, 720)
		<< device_image1.copy_to(d.data())
		<< synchronize();

	Window window{ "Display", uint2{ 1280,720 } };
	window.set_key_callback([&](int key, int action) noexcept
	{
		if (action == GLFW_PRESS && key == GLFW_KEY_ESCAPE)
		{
			window.set_should_close();
		}
	});
	auto frame_count = 0u;
	window.run([&]
	{
		window.set_background(d.data(), uint2{ 1280,720 });
	});
}
```
When running this code you should be able to see RGB + white color bars, however if you run with an AMD gpu you can only see red, black, green.
From what I've been experimenting with, this seems due to READ_BUFFER(ba11,l12,l9,bdls0) in generated HLSL code. When indexing variable (l9 here) it cannot give expected result, however if we change it to like READ_BUFFER(ba11,l12,2,bdls0) it works.
Any clue on this bug? Thanks.

**Comment by MaxwellGengYF** [comment]
We have tested this instance in next-branch with new dx backend implementation. Under Radeon RX 6900 XT the result is exactly same as under RTX 3080. In next-branch, we are using new version DXC: https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2212
So we may need more experiments to find out whether the problem is from hardware,, driver, or compiler.

**Comment by swfly** [comment]
@MaxwellGengYF Thank you for the information. 
Sorry I forgot to mention we were using master branch for dev at the moment. I also tried with the latest dxc but no difference. Do you think we should switch to the "next" branch? There seem quite some changes so I am a bit hesitating.

**Comment by MaxwellGengYF** [comment]
Firstly master-branch will definitely become deprecated in the future. But the next-branch is under massive refactoring. We are revising some APIs and currently only DirectX backend is functional (other backends still require some time to repair).. BTW, python binding is currently only supported by xmake compiling workflow: https://xmake.io/

**Comment by swfly** [comment]
Yes that's the problem stops us from sticking with latest commit. Even we just started to move to luisacompute within one month we've achieved quite some good result. Switching to next-branch might need some extra effort to us. Anyways, is it possible for you to check the instance above with master branch and see if it can be fixed easily? If not, we might have to start adopting next-branch.

**Comment by Mike-Leo-Smith** [comment]
Yes, we are looking into this. The main difference between the branches is that we switched to Byte Addressed Buffers to implement the Bindless Array. We will investigate if this causes the different behaviors…

**Comment by Mike-Leo-Smith** [comment]
Hi, @swfly 

We switched to the `ByteAddressedBuffer` implementation in 6fa4cdb and it seems to solve the issue on our AMD hardware (6900XT). Would you please try if it works on your side?

**Comment by swfly** [comment]
@Mike-Leo-Smith Wow that's amazing, didn't expect it to be done so quickly. Thank you so much.
I am running the test code on a 7900xt and it works well. However, when I go back to the actual renderer, it's still buggy (while the behavior is different from that before this modification), and driver crashes. I think there could be some other problem to be solved, not sure if it's still related to bindless array though. Please let me confirm first and then come to close this issue.
