### ISSUE TITLE
test_path_tracing in dx has strange aliasing on AMD GPUs

### ISSUE THREAD

**Issue by swfly** [LuisaGroup/LuisaCompute#68]
Hello has anyone tried to run test_path_tracing on AMD GPU? When i try it on 7900xt with master-branch I can see obvious aliasing on edges of meshes. I also observe change of pattern by setting different block size.
I tried to use latest next-branch to test but failed to compile the dx backend (member_reflect.inl reports error with MSVC). Now I am wondering if this is an issue on AMD's side.

**Comment by Mike-Leo-Smith** [comment]
Also, would you help to see if other tests like `test_rtx` and `test_sdf_renderer` runs normally on AMD?

**Comment by swfly** [comment]
Hi @Mike-Leo-Smith 
`test_rtx` and `test_sdf_renderer` works fine on amd from what i can observe. I changed the offset_ray_origin as you mentioned but nothing changes in `test_path_tracing` (i don't see any use of this function there though). I've actually simplified the kernel in `test_path_tracing` to

`
    Kernel2D raytracing_kernel = [&](ImageFloat image, ImageUInt seed_image, AccelVar accel, UInt2 resolution) noexcept 
    {
        auto coord = dispatch_id().xy();
        auto frame_size = min(resolution.x, resolution.y).cast<float>();
        auto pixel = (make_float2(coord)) / frame_size * 2.0f - 1.0f;
        auto ray = generate_ray(pixel * make_float2(1.0f, -1.0f));

        image.write(dispatch_id().xy(), make_float4(0.f,0.f,0.f, 1.0f));
        auto hit = accel.trace_closest(ray);
        $if(!hit->miss())
        {
            auto triangle = heap.buffer<Triangle>(hit.inst).read(hit.prim);
            auto p0 = vertex_buffer.read(triangle.i0);
            auto p1 = vertex_buffer.read(triangle.i1);
            auto p2 = vertex_buffer.read(triangle.i2);
            auto p = hit->interpolate(p0, p1, p2);
            auto n = normalize(cross(p1 - p0, p2 - p0));
            image.write(dispatch_id().xy(), make_float4(n * .5f + .5f, 1.0f));
        };
    };
`
And the aliasing looks like this:
![test_path_tracing](https://user-images.githubusercontent.com/6338825/221514254-30adabbe-bd84-45f4-860f-357e11aca88d.png)

Strangely, I also tried to visualize the 3 components of Hit struct (to visualize inst and prim I hashed the number to get 3 floats). Only the barycentric coordinate has aliasing, and, different from the aliasing pattern in the above image (for barycentric there are only slight grids on the surface).
![test_path_tracing0](https://user-images.githubusercontent.com/6338825/221517399-daaa2c48-09b1-4650-bbe3-5c8a0acf485b.png)

However I think it's not related to alignment of "Triangle" struct because I tried to change it to uint4 and got the same result.
That's all the information I've got.

**Comment by Mike-Leo-Smith** [comment]
Thanks or the information.

@AirGuanZ pointed out that the aliasing pattern might relate to [NonUniformResourceIndex](https://www.asawicki.info/news_1608_direct3d_12_-_watch_out_for_non-uniform_resource_index). I pushed a patch a08df64f and hopefully it will solve the problem.

**Comment by MaxwellGengYF** [comment]
I try to run this example with NonUniformResourceIndex and it works correctly on RX 6900xt.
https://learn.microsoft.com/en-us/windows/win32/direct3d12/resource-binding-in-hlsl

**Comment by swfly** [comment]
Yes it solves almost every problem of our renderer on 7900xt. Now we can finally render on AMD GPUs. Thanks @Mike-Leo-Smith and @MaxwellGengYF . 

This reminds me of my previous issue, probably they are actually pointing to the same problem of AMD's driver mechanic that assuming index to be uniform and optimize? However, I tried to reset to https://github.com/LuisaGroup/LuisaCompute/commit/cd207189f4852debae30f8521b2f06e461bc10b1 and run the test as in #67 with NonUniformResourceIndex, but it failed! 

Also regarding to the compiler error, I think it's OK since I can update my visual studio here.

**Comment by Mike-Leo-Smith** [comment]
> Yes it solves almost every problem of our renderer on 7900xt. Now we can finally render on AMD GPUs.

That sounds really great!

BTW, is the renderer you are working on a production one or a research project? We're very happy to see LuisaCompute utilized in other projects and always very willing to learn more about how users think about or expect from our framework if you would like to share.

> However, I tried to reset to [cd20718](https://github.com/LuisaGroup/LuisaCompute/commit/cd207189f4852debae30f8521b2f06e461bc10b1) and run the test as in #67 with NonUniformResourceIndex, but it failed!

I think it's because the test program in #67 doesn't actually use a non-uniform resource index since there is only one buffer in the bindless array. So this indicates #67 and this one are two different issues. Thanks for digging them out!

**Comment by swfly** [comment]
@Mike-Leo-Smith Thanks for all the support. LuisaCompute is a great framework for performance-centered projects and that's the reason we decided to adopt it in our production renderer. We've been working on our in-house GPU renderer for several years. At its 3rd version, LuisaCompute gives it great boost. Maybe we will release it later this year, but before that, please allow me to keep low key.
Besides, I really wish there could be a place where we can talk more about LuisaCompute, for example feature request or roadmap. Sometimes I really want to contribute a bit to this great project personally, however I need to ask for more information before that, while, I feel it's not appropriate to discuss here.

**Comment by Mike-Leo-Smith** [comment]
@swfly Thanks for the feedback and advice.

We have just opened up this [Discord channel](https://discord.gg/ymYEBkUa7F) for discussion. It’s still under early construction but hopefully could be a better place for quick exchanges of ideas.
