### ISSUE TITLE
-[MTLCompileOptionsInternal setMaxTotalThreadsPerThreadgroup:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by yangfengzzz** [LuisaGroup/LuisaCompute#72]
Mac Ventura(Intel) 13.1 fail run after compile.

There a error about setMaxTotalThreadsPerThreadgroup in Metal-cpp. After I comment it, the program run well because it generate shader cache.

**Comment by Mike-Leo-Smith** [comment]
Hi, @yangfengzzz 

Thanks for reporting this. This method was introduced in macOS 13.3+ so your system failed to find the selector. I fixed it in 4b7857d by adding an availability test before using it.

**Comment by yangfengzzz** [comment]
THX，Pass test on my mac
