### ISSUE TITLE
Assertion with message

### ISSUE THREAD

**Issue by shiinamiyuki** [LuisaGroup/LuisaCompute#81]
**Is your feature request related to a problem? Please describe.**
Currently assertion with message: `assert(cond, "cond is false!")` is only available in Rust frontend and CPU backend.

**Describe the solution you'd like**
Implement the equivalent function of the assert node in IR. The assert node consists of a node refereeing to condition and a string storing the message. 
Proposed solution:
1. Map each string to a unique id consistent between runs.
2. Pass an additional `Buffer<u32> assert_msg_id` to the kernel
3. On a failed assert, before trapping, write the corresponding id to the buffer.
4. The backend detects a runtime error and read back the buffer.

**Describe alternatives you've considered**

**Additional context**

**Comment by Mike-Leo-Smith** [comment]
Implemented on CUDA in 6499dd2. Other backends that do not support `assert` will not implement this feature.
