### ISSUE TITLE
float3x3 implement inconsistent for dx and cuda

### ISSUE THREAD

**Issue by sailing-innocent** [LuisaGroup/LuisaCompute#83]
see the test case src/test/feat/test_buffer.cpp in "next-test" branch, the test case "buffer::float3x3" will act inconsistently in dx and cuda backend:

compile with `xmake` and run with `xmake run test_feat -tc="buffer::float3x3 -sc=dx"` or  `xmake run test_feat -tc="buffer::float3x3 -sc=cuda"`, as shown in figure:
![image](https://github.com/LuisaGroup/LuisaCompute/assets/109784585/beb39085-c93b-4a00-8c76-dbfe50b3f9b9)

this test case will fill two float3x3 a and b and add them together, then save the result to c. The value in c shall be all 2.0f as expected/

dx backend will pass the test case as expected but cuda backend will find itself mistaken when index = 3 or 7, maybe because the value is casted in 4 but not 3?

**Comment by sailing-innocent** [comment]
the copy_from method for float3x3 is ambious for dx and cuda backends

**Comment by MaxwellGengYF** [comment]
The test is in-correct because reading alignment bytes is undefined behavior.
