### ISSUE TITLE
Vulkan support?

### ISSUE THREAD

**Issue by entropylost** [LuisaGroup/LuisaCompute#91]
I recently stumbled across this, and I was wondering if there's any plans to have Vulkan support? This would seem to be the case based on cursory examination of the bootstrap code, but I'd like to confirm, as otherwise using an AMD card on Linux wouldn't be possible.

Apart from that, this seems really neat.

**Comment by Mike-Leo-Smith** [comment]
Hi, @iMplode-nZ 

The Vulkan backend is still work in progress. We encountered with some issues regarding codegen quality, hardware/driver support etc., so we put it aside with lower priority at present.

Hopefully we will be able to fully implement it in the future once we see chances of better driver support as well as fully fledged SPIR-V compilers/optimizers. We would really appreciate it if you have any experience/information to share.

Another way to support AMD cards on Linux might be using the ROCm/HIP ecosystem, which has nearly identical interfaces as NVIDIA's CUDA. So, maybe it's just possible to port the CUDA backend to HIP with some simple modifications?

**Comment by entropylost** [comment]
Hi @Mike-Leo-Smith 

I won't be needing full destination support any time soon, and it does seem like HIP could do basically the same job (at least until I need to start supporting Intel GPUs).
Thanks for the clarification though.
